### ISSUE TITLE
maybe there is a bug in dict_match.py

### ISSUE THREAD

**Issue by S1s-Z** [kangISU/Conf-MPU-DS-NER#1]
hi, thx for your great work, but maybe i find a mistake in dict_match (although your dict_match.py is the same as Peng, ACL2019).
As you use maximum matching algorithm to get the entity from dict, the different type of dict.txt maybe cause some little difference from using one dict.txt with their type.

**Comment by S1s-Z** [comment]
Such as the European is MISC in one MISC_dict, European Union is ORG in one ORG_dict, once you use  ORG_dict.txt to match the entity first and then use MISC_dict.txt to match European (the order in your code). 
The answer of token 'European' and 'Union' are both wrong. 
The expected answer of European Union is B-ORG,I-ORG, but we finally get B-MISC, I-ORG

**Comment by kangISU** [comment]
yes, the matching order matters in the code. It can be further improved, though in the DS setting labeling noise is acceptable.
