### ISSUE TITLE
Question about dictionaries

### ISSUE THREAD

**Issue by S1s-Z** [kangISU/Conf-MPU-DS-NER#4]
hi, may I know the result of BC5CDR (Big Dict) in Table 2 is based on which dictionary? chemicalBigDic.txt / diseaseBigDic.txt or Chemical.txt / Disease.txt in your github dictionaries folder?

**Comment by kangISU** [comment]
Chemical.txt and Disease.txt. FYI, the used dictionaries for chemical and disease are released by AutoNER. For example, Chemical.txt is their core dictionary, while chemicalBigDic.txt is their full dictionary. chemicalBigDic.txt and diseaseBigDic.txt are used only for the additional lexicon feature engineering, not for distant labeling. Sorry about the confusion.
