### ISSUE TITLE
Question about the prior estimation

### ISSUE THREAD

**Issue by www-Ye** [kangISU/Conf-MPU-DS-NER#5]
Notice that the prior estimates for the CoNLL2003 dataset, the numbers in your paper are different from the ones in the code, which one is accurate please

**Comment by kangISU** [comment]
Thanks for pointing this out. Please use the priors in the code. TIcE will give different estimations for different labeling sources (small dict, big dict, kb, etc). We did not observe significant differences in the performances using different prior estimations.
